name: vaden_workspace
publish_to: none
environment:
  sdk: ^3.9.2
workspace:
  - vaden
  - flutter_vaden
  - flutter_vaden/example
  - vaden_core
  - vaden/example
  - vaden_class_scanner
  - vaden_generator/backend
  - vaden_generator/frontend
  - packages/vaden_security
  - examples/todo/app
  - examples/todo/domain
  - examples/todo/backend
