name: vaden_security
description: A Dart package for security-related functionalities. Vaden is a Backend Framework Using Dart.
version: 1.0.0
repository: https://github.com/Flutterando/vaden

resolution: workspace

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  vaden: ^1.0.0
  dart_jsonwebtoken: ^3.2.0
  bcrypt: ^1.1.3
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
