name: todo_backend
description: todo.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  vaden: ^1.0.0
  drift: ^2.27.0
  sqlite3: ^2.7.6
  domain:
  vaden_security:

dev_dependencies:
  build_runner: ^2.10.3
  drift_dev: ^2.27.0
  vaden_class_scanner: ^1.0.0
