name: vaden_class_scanner
description: Dart backend project create by Flutterando community. Using and action!
version: 1.0.2
repository: https://github.com/Flutterando/vaden

environment:
  sdk: ^3.10.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  source_gen: ^4.0.0
  analyzer: ">=8.0.0 <9.0.0"
  build: ^4.0.0
  vaden_core: ^1.0.1
  glob: ^2.1.3
  path: ^1.9.1
  dart_style: ^3.0.1
  collection: ^1.19.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.10.3
  lints: ^6.0.0
  test: ^1.24.0
